export const projects = [
  {
    id: '01', name: 'MES OEE Machine & SAP Integration', category: 'INDUSTRIAL IoT', type: 'mes',
    company: 'PT Trimitra Chitrahasta', year: 'MANUFACTURING',
    intro: 'A production monitoring system connecting 10 PLC machines to operator kiosks, live OEE dashboards, and SAP production confirmation.',
    highlights: ['Production orders, BOM validation & machine interlock', 'Live OK/NG output, downtime & OEE monitoring', 'Reports by order and machine for production planners'],
    tags: ['React', 'MQTT', 'Node-RED', 'SAP ECC'], metric: '10', unit: 'PLC machines connected',
    detail: 'A three-tier Manufacturing Execution System connecting 10 PLC machines through Modbus, MQTT, and Node-RED. Live OEE monitoring makes production performance visible, while automatic SAP production confirmation connects operations to the enterprise.',
    sections: [
      { title: 'Operator kiosk & machine authorization', points: ['Designed and developed a three-tier Manufacturing Execution System (MES), covering operator input, real-time monitoring, and management reporting.', 'Built a kiosk dashboard where operators submit production orders against Bill of Material (BOM) data. The workflow triggers an interlock release signal authorizing the machine to begin production.'] },
      { title: 'Real-time machine monitoring & SAP confirmation', points: ['Captured machine output through PLCs using Modbus, streamed it through MQTT, and processed it in Node-RED before displaying live results.', 'Displayed OK/NG (good and rejected) output, Availability, and Overall Equipment Effectiveness (OEE) per machine, together with order history and downtime logs.', 'Integrated direct production quantity confirmation to SAP, reducing dependence on manual data entry.'] },
      { title: 'Reporting for production planning', points: ['Built an OEE reporting dashboard segmented by production order and machine.', 'Gave production planners evaluation data to assess planning effectiveness and support cost-saving decisions for future production runs.'] },
    ],
    outcome: 'Connected 10 PLC machines across stamping, assembly, and welding lines. Operators, production planners, and management can use the same production data from the factory floor through to SAP.',
    stack: ['ReactJS', 'Express.js', 'PostgreSQL', 'MQTT', 'Node-RED', 'PLC / Modbus', 'SAP ECC', 'SOAP API'],
    flow: ['PLC / Modbus', 'MQTT + Node-RED', 'OEE dashboard', 'SAP confirmation'],
  },
  {
    id: '02', name: 'E-Manifest & Multi-System API Gateway', category: 'SYSTEM ARCHITECTURE', type: 'gateway',
    company: 'PT Trimitra Chitrahasta', year: 'LOGISTICS',
    intro: 'A centralized API gateway that routes requests to e-Manifest, Speed, and SMART LMS through one controlled entry point on GCP.',
    highlights: ['Nginx routing to three backend services', '.NET 8 APIs with authentication & IP restrictions', 'Docker deployments through Azure DevOps CI/CD'],
    tags: ['.NET 8', 'Docker', 'Nginx', 'GCP'], metric: '3', unit: 'backend systems unified',
    detail: 'A centralized API Gateway consolidating three logistics and production backends. Custom IP-restriction middleware protects access, while Docker and Azure DevOps CI/CD automate delivery to GCP.',
    sections: [
      { title: 'Gateway & private-network routing', points: ['Designed and implemented an Nginx gateway on a public-facing GCP VM to consolidate client traffic for e-Manifest, Speed, and SMART LMS.', 'Routed requests to isolated backend services using private IP addresses within the GCP Virtual Private Cloud (VPC).'] },
      { title: 'Backend API development', points: ['Developed REST APIs with ASP.NET Core (.NET 8), MongoDB, and MySQL using a Controller–Service–Repository structure.', 'Used denormalized data structures to optimize read and query latency.'] },
      { title: 'Access control & automated deployment', points: ['Implemented Basic Authentication and custom gateway IP-restriction middleware to block unauthorized direct access that bypasses the gateway.', 'Established an Azure DevOps CI/CD pipeline for containerized Docker deployments to GCP VMs.'] },
    ],
    outcome: 'Unified access to three logistics and production backend systems, with controlled routing and an automated deployment workflow.',
    stack: ['.NET 8', 'MongoDB', 'MySQL', 'Nginx', 'Docker', 'Azure DevOps', 'GCP'],
    flow: ['Production systems', 'Nginx gateway', '.NET 8 services', 'GCP infrastructure'],
  },
  {
    id: '03', name: 'SAP Purchase Requisition & Purchase Order', category: 'ENTERPRISE INTEGRATION', type: 'sap',
    company: 'PT Trimitra Chitrahasta & Dharma Group', year: 'ENTERPRISE',
    intro: 'A Laravel web application for creating, managing, and approving SAP purchase requisitions and purchase orders without requiring users to operate SAP GUI.',
    highlights: ['Single & bulk approval, reversal, and multi-PR upload', 'Reuses existing SAP SOAP transaction APIs', 'Multi-company support for nine Dharma subsidiaries'],
    tags: ['Laravel', 'SAP ECC', 'SOAP API'], metric: '9', unit: 'subsidiaries in scope',
    detail: 'Replaced complex SAP transaction screens with a web-based procurement workflow for non-SAP users. The application covers Purchase Requisition (PR) transactions ME51N, ME52N, ME53N, and ME5A, plus Purchase Order (PO) transactions ME21N, ME22N, and ME23N.',
    sections: [
      { title: 'Procurement creation & approval', points: ['Built PR/PO creation and management in Laravel, including single and bulk approve/unapprove actions and multi-PR upload.', 'Made SAP procurement operations accessible through a web interface without requiring full SAP GUI access.'] },
      { title: 'Bulk operations using existing SAP APIs', points: ['Engineered bulk approval and multi-PR upload by orchestrating repeated calls to existing single-transaction SAP APIs.', 'Avoided the cost and lead time of requesting new custom APIs from SAP consultants.'] },
      { title: 'Standalone multi-company application', points: ['Redesigned the solution around SAP company codes and prefixes to support all nine Dharma Group subsidiaries.', 'Allowed each subsidiary to adapt the interface to its own business process.', 'Presented the solution at Dharma Group’s IT Forkom, including the projected savings under wider adoption.'] },
    ],
    outcome: 'At TCH, approximately 15 PR users could operate without individual SAP named-user licenses, reducing company-wide usage from 50 to about 35 seats and contributing to an estimated IDR 500+ million in annual license savings. Projected group-wide savings are IDR 2.5–4.5 billion per year, depending on adoption across the nine subsidiaries.',
    stack: ['Laravel', 'SAP ECC', 'SOAP API', 'MySQL'],
    flow: ['Purchase request', 'Web approval', 'SOAP integration', 'SAP PR / PO'],
  },
  {
    id: '04', name: 'Warehouse Management System (WMS)', category: 'OPERATIONS', type: 'warehouse',
    company: 'PT Trimitra Chitrahasta', year: 'WAREHOUSING',
    intro: 'Two SAP-integrated warehouse applications: one handles barcode receiving and FIFO stock movement; the other manages production material planning and storage configuration.',
    highlights: ['Barcode receiving, Kanban labels & SAP stock posting', 'Min-max stock levels, forecasting & reorder triggers', 'Storage bins, capacity limits & put-away configuration'],
    tags: ['Laravel', 'MySQL', 'SAP ECC'], metric: '2', unit: 'integrated systems',
    detail: 'Two integrated systems for raw-material intake and production planning. Barcode scanning, FIFO tracking, storage-location mapping, and real-time SAP stock synchronization create a shared view of material movement.',
    sections: [
      { title: 'Raw Material WMS · Receiving & warehouse operations', points: ['Built a barcode receiving workflow from vendor Goods Receipt (GR): scan incoming material, automatically print Kanban labels, then scan those labels against chutter/bin locations to track movement and prevent duplicate entries.', 'Implemented first-in, first-out (FIFO) tracking across multiple storage locations, with automated SAP stock posting to remove manual reconciliation.', 'Automated BPB and transfer-document generation with PDF export, replacing manual receiving paperwork.'] },
      { title: 'Production Material WMS · Planning & configuration', points: ['Built min-max inventory control with SAP-style automatic level calculation, demand forecasting, and safety-stock management for production materials.', 'Developed Storage Location (SLOC) and chutter master-data management, including bin-capacity constraints and put-away strategy configuration.', 'Implemented real-time reorder-point monitoring aligned with Material Requirements Planning (MRP), with automated procurement triggers to maintain production material stock levels.'] },
    ],
    outcome: 'Connected warehouse receiving, stock movement, and production material planning to SAP. Barcode validation and automated posting reduce manual paperwork and reconciliation across storage locations.',
    stack: ['Laravel', 'MySQL', 'SAP ECC', 'SOAP API'],
    flow: ['Barcode intake', 'FIFO tracking', 'SLOC mapping', 'SAP stock sync'],
  },
  {
    id: '05', name: 'PolyboxRak Tracker', category: 'ASSET DIGITALIZATION', type: 'tracker',
    company: 'PT Trimitra Chitrahasta', year: 'ASSET TRACKING',
    intro: 'A QR- and Kanban-based system for tracking production boxes, racks, and their contents across the factory floor and logistics chain.',
    highlights: ['QR identifies each polybox; Kanban identifies contents', 'Priority-based scanning with backend validation', 'Field research, process mapping & pre-deployment tests'],
    tags: ['Laravel', 'MySQL', 'QR Code'], metric: '≈1B', unit: 'IDR / year projected loss reduction',
    detail: 'A QR-code-based tracking system for 20,000–30,000 polyboxes moving across production and logistics. The system lays the foundation for approximately IDR 1 billion per year in prevented asset losses; this is a projected impact, not a claim of realized savings.',
    sections: [
      { title: 'Field research & process design', points: ['Observed warehouse and production operations and met stakeholders to map the existing process and gather requirements from the people using it.', 'Designed an end-to-end tracking flow to address recurring losses from untracked or missing polyboxes.'] },
      { title: 'QR identification & Kanban scanning', points: ['Used QR codes to identify individual polyboxes and Kanban codes to identify their contents.', 'Built the full-stack Laravel Blade interface and backend logic for priority-based Kanban scanning and validation.'] },
      { title: 'Validation before field deployment', points: ['Created dummy master data and test cases for the tracking workflow.', 'Ran validation cycles before field deployment to check system reliability at launch.'] },
    ],
    outcome: 'Established the tracking foundation for 20,000–30,000 polyboxes across internal production and external logistics. The portfolio presents approximately IDR 1 billion per year in potential asset-loss reduction as a projected impact.',
    stack: ['Laravel Blade', 'MySQL', 'QR Code'],
    flow: ['QR identification', 'Movement scan', 'Asset history', 'Reconciliation'],
  },
  {
    id: '06', name: 'Hajj Registration & Billing Platform', category: 'FULLSTACK DEVELOPMENT', type: 'billing',
    company: 'CITIFIN · Freelance', year: 'FINTECH',
    intro: 'A Laravel application for CITIFIN that manages Hajj registration, automates billing, and generates debit cards and PDF documents.',
    highlights: ['End-to-end registration & automated billing', 'Debit card and PDF document generation', 'Full-stack development using Laravel and MySQL'],
    tags: ['Laravel', 'PHP', 'MySQL'], metric: 'E2E', unit: 'registration & billing workflow',
    detail: 'An end-to-end registration and billing platform with automated billing, debit card generation, and PDF document creation. Built to keep the administrative journey connected from initial registration to generated documents.',
    sections: [
      { title: 'Registration & billing workflow', points: ['Built the end-to-end web platform as a freelance fullstack developer for CITIFIN, using Laravel, PHP, and MySQL.', 'Automated billing as part of the registration workflow.'] },
      { title: 'Document generation & extensibility', points: ['Implemented debit card generation and PDF document creation.', 'Designed a modular architecture for possible future expansion into KPR and automotive financing products; those extensions are not presented as delivered features.'] },
    ],
    outcome: 'Delivered a connected administrative workflow covering registration, billing, and generated documents.',
    stack: ['Laravel', 'PHP', 'MySQL', 'PDF generation'],
    flow: ['Registration', 'Automated billing', 'Card generation', 'PDF documents'],
  },
] as const;

export const skills = [
  ['Frontend', 'ReactJS', 'Next.js', 'JavaScript', 'HTML / CSS', 'Livewire', 'TailwindCSS', 'Bootstrap', 'SCSS', 'jQuery'],
  ['Backend', 'PHP', 'Laravel', 'CodeIgniter', 'ExpressJS', 'ASP.NET Core'],
  ['Database', 'MySQL', 'PostgreSQL'],
  ['Enterprise & integration', 'SAP ECC', 'SOAP API', 'RESTful API', 'Postman'],
  ['Industrial / IoT', 'Modbus / PLC', 'MQTT', 'Node-RED', 'Open Modsim'],
  ['Cloud & DevOps', 'Docker', 'Git', 'Azure', 'Ubuntu Server', 'GCP'],
];

export const experience = [
  ['Aug 2025 — Present', 'IT Staff · System Development', 'PT Trimitra Chitrahasta · Dharma Group'],
  ['May 2025 — Aug 2025', 'Fullstack Developer · Freelance', 'CITIFIN'],
  ['Feb 2025 — Jul 2025', 'Fullstack Developer', 'PT Alfabizz Teknologi · for Lestari Jaya Raya Logistics'],
  ['Oct 2024 — Jan 2025', 'IT Developer Intern', 'PT Trimitra Chitrahasta'],
  ['Mar 2024 — May 2024', 'Web Developer Intern', 'LuarSekolah'],
  ['Sep 2023 — Feb 2024', 'IT Intern', 'PT Prima Layanan Niaga Suku Cadang'],
];
